vpc_cidr = "10.0.0.0/16"
vpc_name = "BeeQuantAI-prod-vpc"
environment = "prod"
ecr_repository_name = "BeeQuantAI-prod-ecr"
alb_name = "BeeQuantAI-prod-alb"
tg_name = "BeeQuantAI-prod-tg"
alb_sg_name = "BeeQuantAI-prod-alb-sg"
db_sg_name = "BeeQuantAI-prod-db-sg"
rtb_private1a_name = "BeeQuantAI-prod-rtb-private1a"
rtb_private2b_name = "BeeQuantAI-prod-rtb-private2b"
rtb_private3c_name = "BeeQuantAI-prod-rtb-private3c"
rtb_public_name = "BeeQuantAI-prod-rtb-public"
igw_name = "BeeQuantAI-prod-igw"
BeeQuantAI_nat_public1_ap_southeast_2a = "BeeQuantAI-prod-nat-public1-ap-southeast-2a"
BeeQuantAI_nat_public2_ap_southeast_2b = "BeeQuantAI-prod-nat-public2-ap-southeast-2b"
subnet_cidr_blocks = ["10.0.0.0/24", "10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24", "10.0.4.0/24"]
availability_zones = ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2a", "ap-southeast-2b","ap-southeast-2c"]
subnet_names = ["BeeQuantAI-prod-subnet-public1-ap-southeast-2a", "BeeQuantAI-prod-subnet-public2-ap-southeast-2b", "BeeQuantAI-prod-subnet-private1-ap-southeast-2a", "BeeQuantAI-prod-subnet-private2-ap-southeast-2b", "BeeQuantAI-prod-subnet-private3-ap-southeast-2c"]
BeeQuantAI_nat_name = ["BeeQuantAI-prod-nat-public1-ap-southeast-2a", "BeeQuantAI-prod-nat-public2-ap-southeast-2b"]
rds_name = "BeeQuantAI-prod-rds"
ecs_cluster_name = "BeeQuantAI-prod-ecs-cluster"
ecs_task_execution_role = "BeeQuantAI-prod-ecs-task-execution-role"
ecs_task_role = "BeeQuantAI-prod-ecs-task-role"
ecs_task_role_policy = "BeeQuantAI-prod-ecs-task-role-policy"
