vpc_cidr = "10.0.0.0/16"
vpc_name = "BeeQuantAI-uat-vpc"
environment = "uat"
ecr_repository_name = "BeeQuantAI-uat-ecr"
alb_name = "BeeQuantAI-uat-alb"
tg_name = "BeeQuantAI-uat-tg"
alb_sg_name = "BeeQuantAI-uat-alb-sg"
db_sg_name = "BeeQuantAI-uat-db-sg"
rtb_private1a_name = "BeeQuantAI-uat-rtb-private1a"
rtb_private2b_name = "BeeQuantAI-uat-rtb-private2b"
rtb_private3c_name = "BeeQuantAI-uat-rtb-private3c"
rtb_public_name = "BeeQuantAI-uat-rtb-public"
igw_name = "BeeQuantAI-uat-igw"
BeeQuantAI_nat_public1_ap_southeast_2a = "BeeQuantAI-uat-nat-public1-ap-southeast-2a"
BeeQuantAI_nat_public2_ap_southeast_2b = "BeeQuantAI-uat-nat-public2-ap-southeast-2b"
subnet_cidr_blocks = ["10.0.0.0/24", "10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24", "10.0.4.0/24"]
availability_zones = ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2a", "ap-southeast-2b","ap-southeast-2c"]
subnet_names = ["BeeQuantAI-uat-subnet-public1-ap-southeast-2a", "BeeQuantAI-uat-subnet-public2-ap-southeast-2b", "BeeQuantAI-uat-subnet-private1-ap-southeast-2a", "BeeQuantAI-uat-subnet-private2-ap-southeast-2b", "BeeQuantAI-uat-subnet-private3-ap-southeast-2c"]
BeeQuantAI_nat_name = ["BeeQuantAI-uat-nat-public1-ap-southeast-2a", "BeeQuantAI-uat-nat-public2-ap-southeast-2b"]
rds_name = "BeeQuantAI-uat-rds"
ecs_cluster_name = "BeeQuantAI-uat-ecs-cluster"
ecs_task_execution_role = "BeeQuantAI-uat-ecs-task-execution-role"
ecs_task_role = "BeeQuantAI-uat-ecs-task-role"
ecs_task_role_policy = "BeeQuantAI-uat-ecs-task-role-policy"
