name: Deploy
permissions:
  contents: read
  id-token: write
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Confirm version to deploy'
        required: true
        default: ''
      environment:
        description: 'Confirm environment to deploy'
        required: true
        default: ''
jobs:
  deploy:
    environment: ${{ inputs.environment }}
    name: deploy by terraform
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_BORIS }}
      - name: sts get caller identity
        run: aws sts get-caller-identity
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: terraform init
        run: terraform init
      - name: terraform plan
        run: terraform plan
      - name: terraform apply
        run: terraform apply -auto-approve \
          -var="image_uri=$ECR_REGISTRY_BORIS/${{ secrets.ECR_REPOSITORY }}:${{ inputs.version }}" \
          -var="vpc_cidr=${{ secrets.VPC_CIDR }}" \
          -var="vpc_name=${{ secrets.VPC_NAME }}"\
          -var="ecr_repository_name=${{ secrets.ECR_REPOSITORY }}" \
          -var="alb_name=${{ secrets.ALB_NAME }}" \
          -var="tg_name=${{ secrets.TG_NAME }}" \
          -var="alb_sg_name=${{ secrets.ALB_SG_NAME }}" \
          -var="db_sg_name=${{ secrets.DB_SG_NAME }}" \
          -var="rtb_private1a_name=${{ secrets.RTB_PRIVATE1A_NAME }}" \
          -var="rtb_private2b_name=${{ secrets.RTB_PRIVATE2B_NAME }}" \
          -var="rtb_private3c_name=${{ secrets.RTB_PRIVATE3C_NAME }}" \
          -var="rtb_public_name=${{ secrets.RTB_PUBLIC_NAME }}" \
          -var="igw_name=${{ secrets.IGW_NAME }}" \
          -var="BeeQuantAI_nat_public1_ap_southeast_2a=${{ secrets.BEEQUANTAI_NAT_PUBLIC1_AP_SOUTHEAST_2A }}" \
          -var="BeeQuantAI_nat_public2_ap_southeast_2b=${{ secrets.BEEQUANTAI_NAT_PUBLIC2_AP_SOUTHEAST_2B }}" \
          -var="subnet_cidr_blocks=${{ secrets.SUBNET_CIDR_BLOCKS }}" \
          -var="availability_zones=${{ secrets.AVAILABILITY_ZONES }}" \
          -var="subnet_names=${{ secrets.SUBNET_NAMES }}" \
          -var="BeeQuantAI_nat_name=${{ secrets.BEEQUANTAI_NAT_NAME }}" \
          -var="rds_name=${{ secrets.RDS_NAME }}" \
          -var="ecs_cluster_name=${{ secrets.ECS_CLUSTER_NAME }}" \
          -var="ecs_task_execution_role=${{ secrets.ECS_TASK_EXECUTION_ROLE }}" \
          -var="ecs_task_role=${{ secrets.ECS_TASK_ROLE }}" \
          -var="ecs_task_role_policy=${{ secrets.ECS_TASK_ROLE_POLICY }}"
